### ISSUE TITLE
Can't run this on Netlify

### ISSUE THREAD

**Issue by slegay** [11ty/demo-eleventy-edge#1]
Trying to build this on Netlify breaks. I was trying this because we've been building our site on top of 11ty edge and Netlify and this week everything stopped working. Any reference to eleventy:edge in an edge function causes the edge function to crash, it looks like the reference is missing. 

Have there been breaking changes?

EDIT: nevermind, I found your Deno CDN. Updating the import statement to that URL fixed my issue.

**Comment by zachleat** [comment]
Pushing a fix on https://github.com/11ty/eleventy/issues/2572 please subscribe over there!

**Comment by zachleat** [comment]
2.0.0-canary.16 has shipped.
