### ISSUE TITLE
Demo timing out

### ISSUE THREAD

**Issue by LewisDaleUK** [11ty/demo-eleventy-edge#3]
When navigating to https://demo-eleventy-edge.netlify.app, Netlify gives a crashed function report.

<img width="858" alt="This edge function has crashed. An unhandled error in the function code triggered the following message: The deployment failed while serving the request." src="https://user-images.githubusercontent.com/4388406/196123863-53e49251-0433-4740-b5d9-f339ca739947.png">

**Comment by zachleat** [comment]
There is some upstream behind the scenes investigation happening on this one! I’ll keep you updated!

**Comment by zachleat** [comment]
This upstream vendor ticket was officially “resolved” this week so I’d be anxious to learn if you’re still seeing it in the wild!

Thank you!

**Comment by LewisDaleUK** [comment]
Nope! It's all working now - I've been accessing the demos all weekend with no issues
